Clazz.declarePackage ("org.ivis.layout.spring");
c$ = Clazz.declareType (org.ivis.layout.spring, "SpringConstants");
Clazz.defineStatics (c$,
"DEFAULT_NUM_LAYOUT_PASSES", 4,
"DEFAULT_AVERAGE_ITERATIONS_PER_NODE", 40,
"DEFAULT_NODE_DISTANCE_SPRING_SCALARS", [1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
"DEFAULT_NODE_DISTANCE_STRENGTH_CONSTANT", 15,
"DEFAULT_NODE_DISTANCE_REST_LENGTH_CONSTANT", 60,
"DEFAULT_DISCONNECTED_NODE_DISTANCE_SPRING_STRENGTH", 0.05,
"DEFAULT_DISCONNECTED_NODE_DISTANCE_SPRING_REST_LENGTH", 250,
"DEFAULT_ANTICOLLISION_SPRING_SCALARS", [0.0, 1.0, 2.0, 3.0, 4.0, 5.0],
"DEFAULT_ANTICOLLISION_SPRING_STRENGTH", 100);
