# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # workflows use major version specifiers, prefer quick notification
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "quarterly" # package.json uses patch versions, reduce noise
