import define from '../../define/index.mjs';
import * as is from '../../is.mjs';
import * as math from '../../math.mjs';
import * as util from '../../util/index.mjs';
import type { Position } from '../../types.mjs';
import type { Collection, Element } from '../eles-types.mjs';
import type { DataParams } from '../../define/data.mjs';

/** A function that computes a position for an element during `.positions()`. */
export type PositionFn = ( ele: Element, i: number ) => Position | undefined | false;

/**
 * The `.position()`-family accessor. Generated by `define.data`, but typed
 * with position-specific overloads (get returns a Position, set accepts a
 * full/partial Position, a (name, value) pair, or an event handler).
 */
export interface PositionAccessor {
  ( this: Collection ): Position;
  ( this: Collection, pos: Partial<Position> ): Collection;
  ( this: Collection, name: string ): number;
  ( this: Collection, name: string, value: number ): Collection;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- binding overload accepts an arbitrary event handler
  ( this: Collection, handler: ( ...args: any[] ) => void ): Collection;
}

/** Position accessor methods contributed to the collection prototype. */
export interface CollectionPosition {
  position: PositionAccessor;
  silentPosition: PositionAccessor;
  modelPosition: PositionAccessor;
  point: PositionAccessor;
  positions( this: Collection, pos: Partial<Position> | PositionFn, silent?: boolean ): Collection;
  silentPositions( this: Collection, pos: Partial<Position> | PositionFn ): Collection;
  modelPositions( this: Collection, pos: Partial<Position> | PositionFn, silent?: boolean ): Collection;
  points( this: Collection, pos: Partial<Position> | PositionFn, silent?: boolean ): Collection;
  shift( this: Collection, dim: Partial<Position> | string, val?: number | boolean, silent?: boolean ): Collection;
  silentShift( this: Collection, dim: Partial<Position> | string, val?: number ): Collection;
  renderedPosition( this: Collection, dim?: Partial<Position> | string, val?: number ): Position | number | Collection | undefined;
  renderedPoint( this: Collection, dim?: Partial<Position> | string, val?: number ): Position | number | Collection | undefined;
  relativePosition( this: Collection, dim?: Partial<Position> | string, val?: number ): Position | number | Collection | undefined;
  relativePoint( this: Collection, dim?: Partial<Position> | string, val?: number ): Position | number | Collection | undefined;
}

// TODO(eles-types): `locked()` is contributed by the not-yet-converted
// events/selection mixin; cast locally until CollectionEvents declares it.
type WithLocked = { locked(): boolean };

let beforePositionSet = function( eles: Collection, newPos: Partial<Position>, silent: boolean ): void {
  for( let i = 0; i < eles.length; i++ ){
    let ele = eles[i];

    if( !( ele as unknown as WithLocked ).locked() ){
      let oldPos = ele._private.position;

      let delta = {
        x: newPos.x != null ? newPos.x - oldPos.x : 0,
        y: newPos.y != null ? newPos.y - oldPos.y : 0
      };

      if( ele.isParent() && !(delta.x === 0 && delta.y === 0) ){
        ele.children().shift( delta, silent );
      }

      ele.dirtyBoundingBoxCache();
    }
  }
};

// `validKeys` is vestigial (define.data ignores it) but kept to preserve the
// original runtime object exactly.
let positionDef: DataParams<Collection, Element> & { validKeys?: string[] } = {
  field: 'position',
  bindingEvent: 'position',
  allowBinding: true,
  allowSetting: true,
  settingEvent: 'position',
  settingTriggersEvent: true,
  triggerFnName: 'emitAndNotify',
  allowGetting: true,
  validKeys: [ 'x', 'y' ],
  beforeGet: function( ele: Element ){
    ele.updateCompoundBounds();
  },
  beforeSet: function( eles: Collection, newPos: Record<string, unknown> ){
    beforePositionSet( eles, newPos as Partial<Position>, false );
  },
  onSet: function( eles: Collection ){
    eles.dirtyCompoundBoundsCache();
  },
  canSet: function( ele: Element ){
    return !( ele as unknown as WithLocked ).locked();
  }
};

let fn = ({

  position: define.data<Collection, Element>( positionDef ),

  // position but no notification to renderer
  silentPosition: define.data<Collection, Element>( util.assign( {}, positionDef, {
    allowBinding: false,
    allowSetting: true,
    settingTriggersEvent: false,
    allowGetting: false,
    beforeSet: function( eles: Collection, newPos: Record<string, unknown> ){
      beforePositionSet( eles, newPos as Partial<Position>, true );
    },
    onSet: function( eles: Collection ){
      eles.dirtyCompoundBoundsCache();
    }
  } ) as DataParams<Collection, Element> ),

  positions: function( this: Collection, pos: Partial<Position> | PositionFn, silent?: boolean ){
    if( is.plainObject( pos ) ){
      if( silent ){
        this.silentPosition( pos );
      } else {
        this.position( pos );
      }

    } else if( is.fn( pos ) ){
      let fn = pos as PositionFn;
      let cy = this.cy();

      cy.startBatch();

      for( let i = 0; i < this.length; i++ ){
        let ele = this[ i ];
        let pos;

        if( ( pos = fn(ele, i) ) ){
          if( silent ){
            ele.silentPosition( pos );
          } else {
            ele.position( pos );
          }
        }
      }

      cy.endBatch();
    }

    return this; // chaining
  },

  silentPositions: function( this: Collection, pos: Partial<Position> | PositionFn ){
    return this.positions( pos, true );
  },

  shift: function( this: Collection, dim: Partial<Position> | string, val?: number | boolean, silent?: boolean ){
    let delta: Position | undefined;

    if( is.plainObject( dim ) ){
      delta = {
        x: is.number(dim.x) ? dim.x : 0,
        y: is.number(dim.y) ? dim.y : 0
      };

      silent = val as boolean;
    } else if( is.string( dim ) && is.number( val ) ){
      delta = { x: 0, y: 0 };

      delta[ dim as 'x' | 'y' ] = val;
    }

    if( delta != null ){
      let cy = this.cy();

      cy.startBatch();

      for( let i = 0; i < this.length; i++ ){
        let ele = this[i];

        // exclude any node that is a descendant of the calling collection
        if (cy.hasCompoundNodes() && ele.isChild() && ele.ancestors().anySame(this)) {
          continue;
        }

        let pos = ele.position();
        let newPos = {
          x: pos.x + delta.x,
          y: pos.y + delta.y
        };

        if( silent ){
          ele.silentPosition( newPos );
        } else {
          ele.position( newPos );
        }
      }

      cy.endBatch();
    }

    return this;
  },

  silentShift: function( this: Collection, dim: Partial<Position> | string, val?: number ){
    if( is.plainObject( dim ) ){
      this.shift( dim, true );
    } else if( is.string( dim ) && is.number( val ) ){
      this.shift( dim, val, true );
    }

    return this;
  },

  // get/set the rendered (i.e. on screen) positon of the element
  renderedPosition: function( this: Collection, dim?: Partial<Position> | string, val?: number ): Position | number | Collection | undefined {
    let ele = this[0];
    let cy = this.cy();
    let zoom = cy.zoom();
    let pan = cy.pan();
    let rpos = is.plainObject( dim ) ? dim : undefined;
    let setting = rpos !== undefined || ( val !== undefined && is.string( dim ) );

    if( ele && ele.isNode() ){ // must have an element and must be a node to return position
      if( setting ){
        for( let i = 0; i < this.length; i++ ){
          let ele = this[ i ];

          if( val !== undefined ){ // set one dimension
            ele.position( dim as string, ( val - pan[ dim as 'x' | 'y' ] ) / zoom );
          } else if( rpos !== undefined ){ // set whole position
            ele.position( math.renderedToModelPosition( rpos as Position, zoom, pan ) );
          }
        }
      } else { // getting
        let pos = ele.position();
        rpos = math.modelToRenderedPosition( pos, zoom, pan );

        if( dim === undefined ){ // then return the whole rendered position
          return rpos as Position;
        } else { // then return the specified dimension
          return ( rpos as Position )[ dim as 'x' | 'y' ];
        }
      }
    } else if( !setting ){
      return undefined; // for empty collection case
    }

    return this; // chaining
  },

  // get/set the position relative to the parent
  relativePosition: function( this: Collection, dim?: Partial<Position> | string, val?: number ): Position | number | Collection | undefined {
    let ele = this[0];
    let cy = this.cy();
    let ppos = is.plainObject( dim ) ? dim : undefined;
    let setting = ppos !== undefined || ( val !== undefined && is.string( dim ) );
    let hasCompoundNodes = cy.hasCompoundNodes();

    if( ele && ele.isNode() ){ // must have an element and must be a node to return position
      if( setting ){
        for( let i = 0; i < this.length; i++ ){
          let ele = this[ i ];
          let parent = hasCompoundNodes ? ele.parent() : null;
          let hasParent = parent && parent.length > 0;
          let relativeToParent = hasParent;

          if( hasParent ){
            parent = ( parent as Collection )[0];
          }

          let origin = relativeToParent ? ( parent as Collection ).position() : { x: 0, y: 0 };

          if( val !== undefined ){ // set one dimension
            ele.position( dim as string, val + origin[ dim as 'x' | 'y' ] );
          } else if( ppos !== undefined ){ // set whole position
            ele.position({
              x: ( ppos as Position ).x + origin.x,
              y: ( ppos as Position ).y + origin.y
            });
          }
        }

      } else { // getting
        let pos = ele.position();
        let parent = hasCompoundNodes ? ele.parent() : null;
        let hasParent = parent && parent.length > 0;
        let relativeToParent = hasParent;

        if( hasParent ){
          parent = ( parent as Collection )[0];
        }

        let origin = relativeToParent ? ( parent as Collection ).position() : { x: 0, y: 0 };

        ppos = {
          x: pos.x - origin.x,
          y: pos.y - origin.y
        };

        if( dim === undefined ){ // then return the whole rendered position
          return ppos as Position;
        } else { // then return the specified dimension
          return ( ppos as Position )[ dim as 'x' | 'y' ];
        }
      }
    } else if( !setting ){
      return undefined; // for empty collection case
    }

    return this; // chaining
  }
}) as unknown as CollectionPosition;

let elesfn = fn;

// aliases
fn.modelPosition = fn.point = fn.position;
fn.modelPositions = fn.points = fn.positions;
fn.renderedPoint = fn.renderedPosition;
fn.relativePoint = fn.relativePosition;

export default elesfn as CollectionPosition;
