import define from '../../define/index.mjs';
import * as util from '../../util/index.mjs';
import stepAll from './step-all.mjs';
import type { Core, Collection, Element } from '../core-types.mjs';
import type Animation from '../../animation.mjs';
import type { AnimationOptions } from '../../animation.mjs';

/**
 * Animation methods contributed to `Core.prototype` by this mixin. The
 * `.animate()`/`.animation()`/etc. methods are generated by `define`; the
 * loop-management methods are defined here.
 */
export interface CoreAnimation {
  animate( properties: AnimationOptions, params?: AnimationOptions ): Core;
  animation( properties?: AnimationOptions, params?: AnimationOptions ): Animation;
  animated(): boolean | undefined;
  clearQueue(): Core;
  delay( time: number, complete?: () => void ): Core;
  delayAnimation( time: number, complete?: () => void ): Animation;
  stop( clearQueue?: boolean, jumpToEnd?: boolean ): Core;
  /** @internal */
  addToAnimationPool( eles: Collection | Element ): void;
  /** @internal */
  stopAnimationLoop(): void;
  /** @internal */
  startAnimationLoop(): void;
}

// Structural view of the renderer's animation-scheduling hooks.
interface AnimationRenderer {
  beforeRender?( fn: ( willDraw: boolean, now: number ) => void, priority?: number ): void;
  beforeRenderPriorities: { animations: number };
}

let corefn = ({

  // pull in animation functions
  animate: define.animate<Core>(),
  animation: define.animation<Core>(),
  animated: define.animated<Core>(),
  clearQueue: define.clearQueue<Core>(),
  delay: define.delay<Core>(),
  delayAnimation: define.delayAnimation<Core>(),
  stop: define.stop<Core>(),

  addToAnimationPool: function( this: Core, eles: Collection | Element ){
    let cy = this; // eslint-disable-line @typescript-eslint/no-this-alias

    if( !cy.styleEnabled() ){ return; } // save cycles when no style used

    cy._private.aniEles.merge( eles );
  },

  stopAnimationLoop: function( this: Core ){
    this._private.animationsRunning = false;
  },

  startAnimationLoop: function( this: Core ){
    let cy = this; // eslint-disable-line @typescript-eslint/no-this-alias

    cy._private.animationsRunning = true;

    if( !cy.styleEnabled() ){ return; } // save cycles when no style used

    // NB the animation loop will exec in headless environments if style enabled
    // and explicit cy.destroy() is necessary to stop the loop

    function headlessStep(){
      if( !cy._private.animationsRunning ){ return; }

      util.requestAnimationFrame( function animationStep( now: number ){
        stepAll( now, cy );
        headlessStep();
      } );
    }

    let renderer = cy.renderer() as unknown as AnimationRenderer | null;

    if( renderer && renderer.beforeRender ){ // let the renderer schedule animations
      renderer.beforeRender( function rendererAnimationStep( willDraw: boolean, now: number ){
        stepAll( now, cy );
      }, renderer.beforeRenderPriorities.animations );
    } else { // manage the animation loop ourselves
      headlessStep(); // first call
    }
  }

}) satisfies CoreAnimation;

export default corefn;
