// Round 46.5: deciding what the status site contains, separately from writing it.
//
// `buildPlan()` is pure and cheap — stat calls only.  `executePlan()` in
// `scripts/status-build.mjs` is the only thing that touches the filesystem.
// That split is what lets the site's specs run without copying 48 MiB of
// fixtures, and it is what lets the runtime-asset check run over the *intended*
// output rather than over a tree it had to build first.
//
// An op is one output file:
//
//   { kind: 'copy',    from, to }      byte-for-byte
//   { kind: 'jsonmin', from, to }      JSON.parse -> JSON.stringify
//   { kind: 'write',   to, text }      generated
//   { kind: 'omit',    to, reason }    planned, deliberately absent, with why
//
// `to` is always the path *inside* the site — and for every mirrored asset it
// is the same as its path in the repo.  That invariant is what keeps
// `debug/index.html`'s `../build/cytoscape.umd.js` and `../v3/debug/webgl/*`
// resolving with no source file edited.
import { existsSync, statSync, readFileSync, readdirSync } from 'node:fs';
import { Buffer } from 'node:buffer';
import { join } from 'node:path';

/** Cloudflare Pages refuses a file larger than this. */
export const PAGES_MAX_BYTES = 25 * 1024 * 1024;

export const copy = ( from, to ) => ( { kind: 'copy', from, to } );
export const jsonmin = ( from, to ) => ( { kind: 'jsonmin', from, to } );
export const write = ( to, text ) => ( { kind: 'write', to, text } );
export const omit = ( to, reason ) => ( { kind: 'omit', to, reason } );

/**
 * How a fixture gets to the site.
 *
 * Revised on the maintainer's call (2026-08-05): **prefer the existing remote
 * source wherever one exists.**  Both oversized fixtures are NDEx exports that
 * already live in a bucket, so they load from it rather than being carried.
 *
 * @returns 'remote' | 'jsonmin' | 'copy' | 'omit'
 */
export function fixturePolicy( { bytes, minifiedBytes, remoteUrl = null, max = PAGES_MAX_BYTES } ){
  if( remoteUrl != null ){ return 'remote'; }

  // the v3 fixtures are pretty-printed and the page only ever calls
  // `res.json()`, so whitespace is unobservable — and dropping it takes
  // `em-desktop` off 93.6% of the cap, which is closer than anyone noticed
  if( minifiedBytes != null && minifiedBytes < bytes ){
    return minifiedBytes <= max ? 'jsonmin' : 'omit';
  }

  return bytes <= max ? 'copy' : 'omit';
}

/** Byte length of a file, or null. */
export function sizeOf( path ){
  try {
    return statSync( path ).size;
  } catch{
    return null;
  }
}

/** Byte length after re-serializing, or null when it is not JSON. */
export function minifiedSize( path ){
  try {
    return Buffer.byteLength( JSON.stringify( JSON.parse( readFileSync( path, 'utf8' ) ) ) );
  } catch{
    return null;
  }
}

/**
 * The harness mirror.
 *
 * Two files in the copy differ from the source, and that list is closed —
 * `test/modules/status-site.mjs` diffs `index.html` and fails on a third edit.
 * Everything else is byte-for-byte, because a transform applied to a copy is
 * invisible to `test/modules/debug-harness.mjs`.
 */
export function planDebug( { root, networks, remoteOk = () => true } ){
  const ops = [];
  const warnings = [];
  const dir = join( root, 'debug' );

  if( !existsSync( join( dir, 'index.html' ) ) ){
    return { ops, warnings, available: false, reason: 'debug/index.html is missing' };
  }

  const remoteFor = def => {
    if( def.remoteUrl == null ){ return null; }

    return remoteOk( def.remoteUrl ) ? def.remoteUrl : null;
  };

  // -- the harness's own files --
  for( const file of readdirSync( dir ) ){
    if( file.endsWith( '.json' ) || file.endsWith( '.mjs' ) ){ continue; } // fixtures and tooling
    if( file === 'index.html' || file === 'networks.js' || file === 'livereload-setup.js' ){ continue; }

    ops.push( copy( join( dir, file ), `debug/${file}` ) );
  }

  // edit 1 of 2: livereload injects an http:// script that an https deploy
  // blocks as mixed content, and there is nothing to reload anyway
  ops.push( write( 'debug/livereload-setup.js',
    '// Round 46.5: stubbed by scripts/status-build.mjs.  The hosted harness has\n'
    + '// no livereload server, and the original injects an http:// script that an\n'
    + '// https deploy blocks as mixed content.  Run `npm run watch` for the live one.\n'
    + "console.info( 'status site: livereload disabled (this is a static build)' );\n" ) );

  // edit 2 of 2: the fixture-source flag, injected as a script tag
  ops.push( write( 'debug/status-config.js',
    '// Round 46.5: generated by scripts/status-build.mjs.\n'
    + '// Tells debug/init.js to prefer each network\'s remoteUrl.  Absent locally,\n'
    + '// so `npm run watch` never reaches the network.\n'
    + "window.DEBUG_FIXTURE_SOURCE = 'remote';\n" ) );

  const indexHtml = readFileSync( join( dir, 'index.html' ), 'utf8' );

  ops.push( write( 'debug/index.html', patchDebugHtml( indexHtml ) ) );

  // -- the fixtures --
  const dropped = [];

  for( const [ id, def ] of Object.entries( networks ) ){
    if( def.generated || def.url == null ){ continue; }

    const remote = remoteFor( def );
    const from = def.url.startsWith( '../' )
      ? join( root, def.url.replace( /^\.\.\//, '' ) )
      : join( dir, def.url );
    const to = def.url.startsWith( '../' ) ? def.url.replace( /^\.\.\//, '' ) : `debug/${def.url}`;

    if( ops.some( op => op.to === to ) ){ continue; } // two networks share em-web

    const bytes = sizeOf( from );

    if( bytes == null ){
      warnings.push( `${id}: ${def.url} does not exist` );
      ops.push( omit( to, 'the fixture is missing from this checkout' ) );
      dropped.push( id );
      continue;
    }

    const policy = fixturePolicy( {
      bytes,
      minifiedBytes: minifiedSize( from ),
      remoteUrl: remote
    } );

    if( policy === 'remote' ){ continue; } // the page fetches it; nothing to write

    if( policy === 'omit' ){
      const why = def.remoteUrl != null
        ? `${( bytes / 1048576 ).toFixed( 1 )} MiB, over the 25 MiB Pages cap, and its remote source is not reachable`
        : `${( bytes / 1048576 ).toFixed( 1 )} MiB, over the 25 MiB Pages cap, and it has no remote source`;

      warnings.push( `${id}: omitted — ${why}` );
      ops.push( omit( to, why ) );
      dropped.push( id );
      continue;
    }

    ops.push( policy === 'jsonmin' ? jsonmin( from, to ) : copy( from, to ) );
  }

  // networks.js is appended to, never rewritten: `var networks` is in scope
  // after the source's trailing export hook, so the patch is plain assignment
  // and no regex has to understand the file
  ops.push( write( 'debug/networks.js',
    readFileSync( join( dir, 'networks.js' ), 'utf8' ) + networksPatch( dropped ) ) );

  // the bundle the page loads, at the path it looks for it
  const umd = join( root, 'build', 'cytoscape.umd.js' );

  if( existsSync( umd ) ){
    ops.push( copy( umd, 'build/cytoscape.umd.js' ) );
  } else {
    return { ops, warnings, available: false, reason: 'build/cytoscape.umd.js is missing — run `npm run build`' };
  }

  return { ops, warnings, available: true, reason: null, dropped };
}

/** The two — and only two — edits made to the harness's page. */
export function patchDebugHtml( html ){
  return html.replace(
    '<script src="livereload-setup.js"></script>',
    '<script src="livereload-setup.js"></script>\n    <script src="status-config.js"></script>'
  );
}

/** The tail appended to the copied `networks.js`. */
export function networksPatch( dropped ){
  if( dropped.length === 0 ){
    return '\n// -- generated by scripts/status-build.mjs: every network is available --\n';
  }

  return `\n// -- generated by scripts/status-build.mjs (do not edit) --\n`
    + `// These networks are not available in the hosted preview.  Removing the\n`
    + `// entry is deliberate: a dropdown option that 404s is worse than one that\n`
    + `// is absent, and round 42 shipped four of exactly that.\n`
    + dropped.map( id => `delete networks[${JSON.stringify( id )}];` ).join( '\n' )
    + '\n';
}
