name: npm publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: master
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          package-manager-cache: false
      - name: Publish Package To npmjs
        run: npm publish --provenance
